HAAS-289
trifork/falcon-ig pull request #60
Opened 2023-03-15 10:54 UTC by mjga-trifork

2023-03-17 14:51 UTC, jkiddo commented on input/fsh/codesystems/smart-scopes.fsh
> +* #avmguidance ^property.valueString = "user/avmguidance.rs"
There is no resource called 'avmguidance'

2023-03-17 14:52 UTC, jkiddo requested changes

2023-03-17 14:52 UTC, jkiddo commented on input/fsh/codesystems/smart-scopes.fsh
> +* #clinicalDocument ^property.valueString = "user/clinicalDocument.crs"
this does not follow the smart spec

2023-03-17 14:52 UTC, jkiddo commented on input/fsh/codesystems/smart-scopes.fsh
> +* #personalData ^property.valueString = "user/personalData.r"
this does not follow the smart spec

2023-03-20 07:14 UTC, mjga-trifork commented on input/fsh/codesystems/smart-scopes.fsh
> +* #avmguidance ^property.valueString = "user/avmguidance.rs"
Of course. We need to identify or define Fhir resource types for use her. I guess avmguidance is not a standard fhir resource.

2023-03-29 09:47 UTC, mjga-trifork commented on input/fsh/codesystems/smart-scopes.fsh
> +* #avmguidance ^property.valueString = "user/avmguidance.rs"
I've generalized all these to wildcards

2023-03-29 09:47 UTC, mjga-trifork commented on input/fsh/codesystems/smart-scopes.fsh
> +* #personalData ^property.valueString = "user/personalData.r"
I've generalized all these to wildcards

2023-03-29 09:47 UTC, mjga-trifork commented on input/fsh/codesystems/smart-scopes.fsh
> +* #clinicalDocument ^property.valueString = "user/clinicalDocument.crs"
I've generalized all these to wildcards

2023-03-29 13:11 UTC, merged